#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[ -f ~/.xprofile ] && source ~/.xprofile

xset +dpms 
xset dpms 0 0 300
# sudo powertop --auto-tune &
xrdb -q

# dunst
dunst -config ~/.config/dunst/dunstrc &

# compton
compton --config ~/.config/i3/compton.conf &

xrandr --output DVI-D-1 --mode 1920x1080 --pos 3136x2560 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 1216x2560 --rotate normal --output DP-2 --mode 2560x1440 --pos 2560x0 --rotate left --output DP-1 --primary --mode 2560x1440 --pos 0x1120 --rotate normal --output HDMI-2 --off

exec i3
