#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[ -f ~/.xprofile ] && source ~/.xprofile

xset +dpms 
xset dpms 0 0 300
# sudo powertop --auto-tune &
xrdb -q

# Wallpaper
feh --bg-fill ~/Pictures/wallpaper.jpg

# dunst
dunst -config ~/.config/dunst/dunstrc &

# compton
compton --config ~/.config/i3/compton.conf &

# Network Manager
nm-applet &

# Desktop XRANDR
# xrandr --output DVI-D-0 --off --output DP-2.8 --mode 2560x1440 --pos 1440x1120 --rotate normal --output HDMI-1 --off --output HDMI-0 --primary --mode 1920x1080 --pos 936x2560 --rotate normal --output DP-3 --off --output DP-2 --off --output DP-1 --off --output DP-0 --mode 2560x1440 --pos 0x0 --rotate right

exec i3
