# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="lambda"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker zsh-completions)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Extras
alias vim="lvim"
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin/
. "$HOME/.cargo/env"
export ONOS_ROOT="/opt/onos"
source $ONOS_ROOT/tools/dev/bash_profile
eval `keychain --eval --agents ssh id_ed25519`

# Cuda
export GOPATH=$HOME/go
export PATH=/usr/local/cuda-11.5/bin${PATH:+:${PATH}}
export GO111MODULE=on
export CGO_CFLAGS="-I/usr/local/cuda-11.5/include/"
export PATH=$PATH:/usr/local/cuda/bin/:$GOPATH/bin/cudagen

# ZSH Specific
export GPG_TTY=$(tty)
autoload -U compinit && compinit

# Quality of Life
function ex()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;      
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

UNAME_OS="$(uname)"
UNAME_DISTRO="$(uname -v)"

if [ "$UNAME_OS" == "Linux" ]; then
	alias ls="ls -lAh --color=auto"
elif [ "$UNAME_OS" == "OpenBSD" ]; then
	alias ls="colorls -lah -G"
fi

# package manager commands
if [[ "$UNAME_DISTRO" == *"Debian"* ]] || [[ "$UNAME_DISTRO" == *"Ubuntu"* ]]; then
  alias grab="apt-get install -y"
  alias purge="apt purge -y"
  alias remove="apt autoremove -y"
  alias update="apt update -y"
  alias upgrade="apt upgrade -y"
elif [[ "$UNAME_DISTRO" == *"Arch"* ]]; then
  alias grab="pacman -Syu"
  alias purge="echo 'update this...'"
  alias remove="echo 'update this...'"
  alias update="pacman -Syu"
  alias upgrade="pacman -Syu"
fi

alias l="ls"
alias ..="cd .."
alias cp="cp -i"
alias df="df -h"
alias mv="mv -i"
alias p="upower --dump | grep 'percentage\|state' | sort | uniq"
alias rm="printf 'stop using rm... use tp/tl/te instead...\n'; false"
alias search="apt search"
alias talist="~/.config/talist/src/talist"
alias te="trash-empty"
alias tl="trash-list"
alias tp="trash-put"
alias when="history | grep"
alias vim="nvim"
alias binwalk="binwalk --run-as=root"

alias aarch64="qemu-aarch64-static -L /usr/aarch64-linux-gnu/"

# batcat special case
if type batcat 1>/dev/null 2>/dev/null; then
  alias cat="batcat"
fi
